"""Geometry-safe wrapper for the pile foundation algorithm.

This wrapper keeps the existing pile extraction and the intentional randomized
SP-compliant deviations untouched. It changes only how the generated sheet
bounds are calculated: frame placement must be based on geometry generated by
our algorithm, not on arbitrary source-DXF entities that happen to remain in
modelspace.

No source layer/block names are required for the bounds rule. The generated
layers are our own output contract, so they are safe to use for presentation
geometry while source entities remain available in the resulting DXF.
"""

import algo_piles as _piles
from ezdxf import bbox as ezdxf_bbox

ALGORITHM_NAME = _piles.ALGORITHM_NAME
PREVIEW_IMAGE = getattr(_piles, "PREVIEW_IMAGE", "preview_piles.png")

# Preserve the existing public API and, importantly, the existing random
# deviation generation in algo_piles.
process_dxf_to_asbuilt_scheme = _piles.process_dxf_to_asbuilt_scheme

_GENERATED_LAYERS = {
    "Сваи_Проект",
    "Оси_Проект",
    "Исполнительная_Номера",
    "Исполнительная_Размеры",
    "Исполнительная_Отклонения",
    "Исполнительная_Ростверк",
    "Исполнительная_Оси_Опор",
    "Исполнительная_Оформление",
    "ИСП_Текст",
    "ИСП_Таблица",
    "ИСП_Размеры_Проект",
    "ИСП_Размеры_Факт",
}

_ORIGINAL_EXTENTS = ezdxf_bbox.extents


def _generated_extents(layout):
    """Return bounds only for entities produced by the pile generator."""
    box = ezdxf_bbox.BoundingBox()
    for entity in layout:
        try:
            layer = entity.dxf.layer
            if layer not in _GENERATED_LAYERS:
                continue
            entity_box = _ORIGINAL_EXTENTS([entity])
            if entity_box.has_data:
                box.extend([entity_box.extmin, entity_box.extmax])
        except Exception:
            continue
    return box


def _patched_extents(entities, *args, **kwargs):
    """Intercept only modelspace-wide bbox requests; delegate entity calls."""
    if hasattr(entities, "name") and getattr(entities, "name", None) == "Model":
        return _generated_extents(entities)
    return _ORIGINAL_EXTENTS(entities, *args, **kwargs)


def run(input_dxf, output_dxf, output_csv=None, log_callback=None,
        stamp_data=None, table_data=None):
    """Run the original algorithm with generated-geometry frame bounds."""
    original_extents = ezdxf_bbox.extents
    original_safe_extents = _piles.safe_extents
    ezdxf_bbox.extents = _patched_extents
    _piles.safe_extents = _generated_extents
    try:
        return _piles.run(
            input_dxf,
            output_dxf,
            output_csv,
            log_callback=log_callback,
            stamp_data=stamp_data,
            table_data=table_data,
        )
    finally:
        _piles.safe_extents = original_safe_extents
        ezdxf_bbox.extents = original_extents


def generate_table_data(*args, **kwargs):
    return _piles.generate_table_data(*args, **kwargs)
